package formatgo

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestFormatFiles(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/project\n\ngo 1.25\n"), 0o644))

	filename := filepath.Join(dir, "main.go")
	source := "package main\nimport (\n\"example.com/project/internal/pkg\"\n\"fmt\"\n\"github.com/pkg/errors\"\n)\nfunc main(){fmt.Println(errors.New(pkg.Name))}\n"
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "internal", "pkg"), 0o755))
	require.NoError(t, os.WriteFile(filename, []byte(source), 0o600))

	require.NoError(t, formatFiles([]string{dir}, false, &bytes.Buffer{}))

	formatted, err := os.ReadFile(filename)
	require.NoError(t, err)
	require.Equal(t, `package main

import (
	"fmt"

	"github.com/pkg/errors"

	"example.com/project/internal/pkg"
)

func main() { fmt.Println(errors.New(pkg.Name)) }
`, string(formatted))
	info, err := os.Stat(filename)
	require.NoError(t, err)
	require.Equal(t, os.FileMode(0o600), info.Mode().Perm())
}

func TestFormatFilesDisplayDiffDoesNotWrite(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/project\n\ngo 1.25\n"), 0o644))

	filename := filepath.Join(dir, "main.go")
	source := "package main\nfunc main(){println(\"hello\")}\n"
	require.NoError(t, os.WriteFile(filename, []byte(source), 0o644))

	var output bytes.Buffer
	err := formatFiles([]string{filename}, true, &output)
	require.EqualError(t, err, "1 files should be formatted")
	require.Contains(t, output.String(), "--- "+filename)
	require.Contains(t, output.String(), "+func main() { println(\"hello\") }")

	actual, readErr := os.ReadFile(filename)
	require.NoError(t, readErr)
	require.Equal(t, source, string(actual))
}

func TestFormatFilesSkipsGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	filename := filepath.Join(dir, "generated.go")
	source := "// Code generated by test. DO NOT EDIT.\npackage generated\nfunc value(){println(1)}\n"
	require.NoError(t, os.WriteFile(filename, []byte(source), 0o644))

	require.NoError(t, formatFiles([]string{dir}, false, &bytes.Buffer{}))

	actual, err := os.ReadFile(filename)
	require.NoError(t, err)
	require.Equal(t, source, string(actual))
}
