type (
	{{.lowerStartCamelObject}}Model interface{
		{{.method}}

		// custom interface generated by pzero
	    BulkInsert(ctx context.Context, session sqlx.Session, datas []*{{.upperStartCamelObject}}) error
        FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*{{.upperStartCamelObject}}, error)
        FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*{{.upperStartCamelObject}}, error)
        FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*{{.upperStartCamelObject}}, error)
        FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*{{.upperStartCamelObject}}, error)
        CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error)
        PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*{{.upperStartCamelObject}}, int64 ,error)
        UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conditions ...condition.Condition) error
        DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error
	}

	default{{.upperStartCamelObject}}Model struct {
		cachedConn sqlc.CachedConn
		conn sqlx.SqlConn
		flavor sqlbuilder.Flavor
		table string
	}

	{{.upperStartCamelObject}} struct {
		{{.fields}}
	}
)
