// Code generated by pzero. DO NOT EDIT.

package model

import (
	"time"

	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/polpo-space/pzero/core/stores/modelx"
    "github.com/eddieowens/opts"
	"github.com/zeromicro/go-zero/core/stores/cache"

	{{range $v := .Imports}}"{{$v}}"
	{{end}}
)

{{if .ModelExpiryTable}}
var (
	ModelExpiryTable map[string]int64 = map[string]int64{
		{{range $k, $v := .ModelExpiryTable}}"{{$k}}": {{$v}},
		{{end}}
	}
)
{{end}}

{{if .ModelNotFoundExpiryTable}}
var (
	ModelNotFoundExpiryTable map[string]int64 = map[string]int64{
		{{range $k, $v := .ModelNotFoundExpiryTable}}"{{$k}}": {{$v}},
		{{end}}
	}
)
{{end}}

type Model struct {
    {{range $v := .TableInfos}}{{$v.Name | FirstUpper | ToCamel}} {{$v.Name}}.{{$v.Name | FirstUpper |ToCamel}}Model
    {{end}}
}

func NewModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) Model {
	{{range $v := .TableInfos}}{{if and $.ModelCache (or $v.HasCacheExpiry $v.HasNotFoundExpiry)}}
	{{$v.Name | ToCamel}}CacheOpts := opts.DefaultApply(op...).CacheOpts
	{{if $v.HasCacheExpiry}}
	if expiry, ok := ModelExpiryTable["{{$v.Name}}"]; ok {
		{{$v.Name | ToCamel}}CacheOpts = append({{$v.Name | ToCamel}}CacheOpts, cache.WithExpiry(time.Duration(expiry)*time.Second))
	}
	{{end}}
	{{if $v.HasNotFoundExpiry}}
	if notFoundExpiry, ok := ModelNotFoundExpiryTable["{{$v.Name}}"]; ok {
		{{$v.Name | ToCamel}}CacheOpts = append({{$v.Name | ToCamel}}CacheOpts, cache.WithNotFoundExpiry(time.Duration(notFoundExpiry)*time.Second))
	}{{end}}{{end}}{{end}}
	return Model{
         {{range $v := .TableInfos}}{{if and $.ModelCache (or $v.HasCacheExpiry $v.HasNotFoundExpiry)}}{{$v.Name | FirstUpper | ToCamel}}: {{$v.Name}}.New{{ $v.Name | FirstUpper | ToCamel }}Model(conn, append(op, modelx.WithCacheOpts({{$v.Name | ToCamel}}CacheOpts...))...),{{else}}{{$v.Name | FirstUpper | ToCamel}}: {{$v.Name}}.New{{ $v.Name | FirstUpper | ToCamel }}Model(conn, op...),{{end}}
         {{end}}
	}
}
