-- DO NOT EDIT AS MIGRATION.
-- This file is a schema snapshot only (current structure for review/alignment).
-- Schema changes belong in desc/sql_migration via: <service> migrate create <name>
-- Model code is generated from PostgreSQL datasource (model-datasource: true), not from this file.

CREATE TABLE {{ .Name }} (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
