-- Schema snapshot for {{ .Name }}.
-- desc/sql is documentation of the current schema only.
-- Model code is generated from PostgreSQL datasource (model-datasource: true).
-- Schema changes go through desc/sql_migration via: <service> migrate create <name>

CREATE TABLE {{ .Name }} (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
