// Code generated by pzero. DO NOT EDIT.
package handler

import (
        {{if .UseHTTP}}"net/http"{{end}}
        {{if .UseTime}}"time"{{end}}

        "github.com/zeromicro/go-zero/rest"
        "{{.Module}}/internal/svc"{{ if .HandlerImports }}{{ .HandlerImports }}{{ end }}
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
        {{if .Routes}}{{.Routes}}{{end}}
}
