// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pzero/api/zrpc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZrpcRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Middleware    string                 `protobuf:"bytes,1,opt,name=middleware,proto3" json:"middleware,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZrpcRule) Reset() {
	*x = ZrpcRule{}
	mi := &file_pzero_api_zrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZrpcRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZrpcRule) ProtoMessage() {}

func (x *ZrpcRule) ProtoReflect() protoreflect.Message {
	mi := &file_pzero_api_zrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZrpcRule.ProtoReflect.Descriptor instead.
func (*ZrpcRule) Descriptor() ([]byte, []int) {
	return file_pzero_api_zrpc_proto_rawDescGZIP(), []int{0}
}

func (x *ZrpcRule) GetMiddleware() string {
	if x != nil {
		return x.Middleware
	}
	return ""
}

var file_pzero_api_zrpc_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ZrpcRule)(nil),
		Field:         10002,
		Name:          "pzero.api.zrpc",
		Tag:           "bytes,10002,opt,name=zrpc",
		Filename:      "pzero/api/zrpc.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ZrpcRule)(nil),
		Field:         10003,
		Name:          "pzero.api.zrpc_group",
		Tag:           "bytes,10003,opt,name=zrpc_group",
		Filename:      "pzero/api/zrpc.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional pzero.api.ZrpcRule zrpc = 10002;
	E_Zrpc = &file_pzero_api_zrpc_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional pzero.api.ZrpcRule zrpc_group = 10003;
	E_ZrpcGroup = &file_pzero_api_zrpc_proto_extTypes[1]
)

var File_pzero_api_zrpc_proto protoreflect.FileDescriptor

const file_pzero_api_zrpc_proto_rawDesc = "" +
	"\n" +
	"\x14pzero/api/zrpc.proto\x12\tpzero.api\x1a google/protobuf/descriptor.proto\"*\n" +
	"\bZrpcRule\x12\x1e\n" +
	"\n" +
	"middleware\x18\x01 \x01(\tR\n" +
	"middleware:H\n" +
	"\x04zrpc\x12\x1e.google.protobuf.MethodOptions\x18\x92N \x01(\v2\x13.pzero.api.ZrpcRuleR\x04zrpc:T\n" +
	"\n" +
	"zrpc_group\x12\x1f.google.protobuf.ServiceOptions\x18\x93N \x01(\v2\x13.pzero.api.ZrpcRuleR\tzrpcGroupB(Z&github.com/polpo-space/pzero/proto/apib\x06proto3"

var (
	file_pzero_api_zrpc_proto_rawDescOnce sync.Once
	file_pzero_api_zrpc_proto_rawDescData []byte
)

func file_pzero_api_zrpc_proto_rawDescGZIP() []byte {
	file_pzero_api_zrpc_proto_rawDescOnce.Do(func() {
		file_pzero_api_zrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pzero_api_zrpc_proto_rawDesc), len(file_pzero_api_zrpc_proto_rawDesc)))
	})
	return file_pzero_api_zrpc_proto_rawDescData
}

var file_pzero_api_zrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pzero_api_zrpc_proto_goTypes = []any{
	(*ZrpcRule)(nil),                    // 0: pzero.api.ZrpcRule
	(*descriptorpb.MethodOptions)(nil),  // 1: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
}
var file_pzero_api_zrpc_proto_depIdxs = []int32{
	1, // 0: pzero.api.zrpc:extendee -> google.protobuf.MethodOptions
	2, // 1: pzero.api.zrpc_group:extendee -> google.protobuf.ServiceOptions
	0, // 2: pzero.api.zrpc:type_name -> pzero.api.ZrpcRule
	0, // 3: pzero.api.zrpc_group:type_name -> pzero.api.ZrpcRule
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pzero_api_zrpc_proto_init() }
func file_pzero_api_zrpc_proto_init() {
	if File_pzero_api_zrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pzero_api_zrpc_proto_rawDesc), len(file_pzero_api_zrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_pzero_api_zrpc_proto_goTypes,
		DependencyIndexes: file_pzero_api_zrpc_proto_depIdxs,
		MessageInfos:      file_pzero_api_zrpc_proto_msgTypes,
		ExtensionInfos:    file_pzero_api_zrpc_proto_extTypes,
	}.Build()
	File_pzero_api_zrpc_proto = out.File
	file_pzero_api_zrpc_proto_goTypes = nil
	file_pzero_api_zrpc_proto_depIdxs = nil
}
