name: goreleaser-pzero

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.25.0'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to ghcr
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/polpo-space/pzero
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ !contains(github.ref_name, '-') }}

      - name: Docker build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  tag_cmd_pzero:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.25.0'
      - name: release pzero cmd
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          if git ls-remote --exit-code --tags origin "refs/tags/cmd/pzero/${VERSION}"; then
            echo "cmd/pzero/${VERSION} already exists"
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          cd cmd/pzero
          GOWORK=off go mod edit -dropreplace github.com/polpo-space/pzero
          GOWORK=off GOPROXY=direct go get "github.com/polpo-space/pzero@${VERSION}"
          GOWORK=off GOPROXY=direct go mod tidy
          sed -i "s/version = \".*\"/version = \"${VERSION}\"/g" main.go
          git add go.mod go.sum main.go
          git commit -m "chore(pzero): release ${VERSION}"
          git tag "cmd/pzero/${VERSION}"
          git push origin "cmd/pzero/${VERSION}"
