// Code generated by pzero. DO NOT EDIT.
package handler

import (
	"github.com/zeromicro/go-zero/rest"

	"{{.Module}}/internal/svc"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {}
